os: linux
dist: xenial
branches:
  only:
    - master
before_install:
  - sudo apt-get update --quiet
  - sudo apt-get install graphviz -y
  - pip install poetry
language: python
python:
  - "3.7"
  - "3.8"
install:
  - poetry install -v
services:
  - postgresql
script:
  - poetry run pytest --verbose
notifications:
  email:
    on_success: change
    on_failure: always
